### ISSUE TITLE
ampモードにするとamp-imgでエラーとなる

### ISSUE THREAD

**Issue by chucker34** [mirucon/coldbox-addon#14]
google search consoleより確認できたのですが
設定にてAMP ページを利用するにチェックを入れると
`amp-tag`のところでエラーが起こっています

search console上でのエラーは下記です
>AMP HTML タグの属性で指定されたレイアウトが無効です。

恐らくwidthとheight属性が指定されていないことによるものかと思います

**Comment by mirucon** [comment]
申し訳ないですが、現状のプラグインでは、元々の img タグに width, height 属性がついていない時の自動付与機能はつけていません。また、機能の実装予定も未定となっております。

元々の img タグにそれらの属性をつけていただくか、公式の AMP プラグインをご使用になる（この場合はテーマの機能は無効化していただく必要があります）かのご対応をお願いいたします。
